sudo: false

language: cpp

compiler:
  -gcc

before_install:
  - pip install --user cpp-coveralls

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
  - mkdir build
  - cd build
  - cmake ..
  - make

script:
  - ctest -V

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
