sudo: false

language: cpp

compiler:
  -gcc

before_install:
  - pip install --user cpp-coveralls

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5.0" CC="gcc-5.0"; fi
  - mkdir build
  - cd build
  - cmake ..
  - make

script:
  - ctest -V

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-5.0
    packages:
    - gcc-5.0
    - g++-5.0
